CREATE TABLE IF NOT EXISTS alerts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id INT NOT NULL REFERENCES alert_source_info(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL default (now() at time zone 'utc'),
  last_updated TIMESTAMPTZ NOT NULL default (now() at time zone 'utc'),
  state VARCHAR NOT NULL,
  assigned_user_id INT REFERENCES users(id) ON DELETE SET NULL,
  subject VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  priority VARCHAR NOT NULL,
  entity VARCHAR NOT NULL,
  entity_group VARCHAR NOT NULL,
  timeout INT NOT NULL default 60,
  first_callback_at TIMESTAMPTZ,
  last_callback_at TIMESTAMPTZ
)