-- Your SQL goes here
CREATE TABLE IF NOT EXISTS subscription (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id INT REFERENCES alerts(id) ON DELETE CASCADE,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  granularity VARCHAR NOT NULL,
  notification_channel INT REFERENCES notification_channel(id) ON DELETE CASCADE
);