CREATE TABLE IF NOT EXISTS incident_report (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  segments_lost DECIMAL(2) NOT NULL,
  loss_details TEXT NOT NULL,
  cost DECIMAL(2) NOT NULL,
  tta INTERVAL NOT NULL,
  ttr INTERVAL,
  status VARCHAR NOT NULL,
  resolution TEXT NOT NULL,
  created_at TIMESTAMPTZ default (now() at time zone 'utc'),
  last_updated TIMESTAMPTZ default (now() at time zone 'utc')
);

CREATE TABLE IF NOT EXISTS incident_alert (
  incident_id INT REFERENCES incident_report(id) ON DELETE CASCADE,
  alert_id INT REFERENCES alerts(id) ON DELETE CASCADE,
  PRIMARY KEY (incident_id, alert_id)
);