CREATE TABLE IF NOT EXISTS user_notes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note TEXT,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  alert_id INT REFERENCES alerts(id) ON DELETE CASCADE,
  visibility VARCHAR NOT NULL CHECK (visibility IN ('Public', 'Private')),
  created_at TIMESTAMPTZ default (now() at time zone 'utc'),
  last_updated TIMESTAMPTZ default (now() at time zone 'utc')
);